# Generated by Django 5.1.1 on 2024-11-27 06:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_saran', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('isi_konten', ckeditor.fields.RichTextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dilihat', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(upload_to='konten_foto/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_konten', 'Can add konten'), ('can_change_konten', 'Can change konten'), ('can_delete_konten', 'Can delete konten'), ('can_view_konten', 'Can view konten')],
            },
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='user_cms.konten')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('komen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_cms.komen')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='user_cms.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
