# Generated by Django 5.1.1 on 2024-12-10 08:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_saran', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Saran',
                'verbose_name_plural': 'Saran',
            },
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komen',
                'verbose_name_plural': 'Komen User',
            },
        ),
        migrations.CreateModel(
            name='Balasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='user_cms.balasan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('komen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user_cms.komen')),
            ],
            options={
                'verbose_name': 'Balasan',
                'verbose_name_plural': 'Balasan User',
            },
        ),
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('isi_konten', ckeditor.fields.RichTextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dilihat', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(upload_to='konten_foto/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konten',
                'verbose_name_plural': 'Konten User',
                'ordering': ['judul'],
                'permissions': [('can_add_konten', 'Can add konten'), ('can_change_konten', 'Can change konten'), ('can_delete_konten', 'Can delete konten'), ('can_view_konten', 'Can view konten')],
            },
        ),
        migrations.AddField(
            model_name='komen',
            name='konten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='user_cms.konten'),
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('komunitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.komunitas')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pertanyaan',
                'verbose_name_plural': 'Pertanyaan Komunitas',
            },
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_set', to='user_cms.pertanyaan')),
            ],
            options={
                'verbose_name': 'Jawaban Pertanyaan',
                'verbose_name_plural': 'Jawaban Pertanyaan',
            },
        ),
    ]
