# Generated by Django 5.1.1 on 2024-11-17 16:41

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0002_remove_konten_kategori_remove_konten_user'),
        ('user_cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('isi_konten', ckeditor.fields.RichTextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dilihat', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(upload_to='konten_foto/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_konten', 'Can add konten'), ('can_change_konten', 'Can change konten'), ('can_delete_konten', 'Can delete konten'), ('can_view_konten', 'Can view konten')],
            },
        ),
        migrations.AlterField(
            model_name='komen',
            name='konten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='user_cms.konten'),
        ),
    ]
