# Generated by Django 5.1.1 on 2024-12-10 09:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konten',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
