# Generated by Django 5.1.1 on 2024-12-10 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0002_alter_konten_isi_konten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konten',
            name='isi_konten',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
