# Generated by Django 5.1.1 on 2024-11-27 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0002_pertanyaan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Balasan',
        ),
        migrations.AlterModelOptions(
            name='balasan',
            options={'verbose_name': 'Balasan', 'verbose_name_plural': 'Balasan User'},
        ),
        migrations.AlterModelOptions(
            name='komen',
            options={'verbose_name': 'Komen', 'verbose_name_plural': 'Komen User'},
        ),
        migrations.AlterModelOptions(
            name='pertanyaan',
            options={'verbose_name': 'Pertanyaan', 'verbose_name_plural': 'Pertanyaan User'},
        ),
    ]
