# Generated by Django 5.1.1 on 2024-11-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0003_rename_reply_balasan_alter_balasan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konten',
            options={'permissions': [('can_add_konten', 'Can add konten'), ('can_change_konten', 'Can change konten'), ('can_delete_konten', 'Can delete konten'), ('can_view_konten', 'Can view konten')], 'verbose_name': 'Konten', 'verbose_name_plural': 'Konten User'},
        ),
        migrations.AlterModelOptions(
            name='saran',
            options={'verbose_name': 'Saran', 'verbose_name_plural': 'Saran'},
        ),
    ]
