# Generated by Django 5.1.1 on 2024-11-27 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0004_alter_konten_options_alter_saran_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
