# Generated by Django 5.1.1 on 2024-12-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0005_alter_pertanyaan_isi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konten',
            options={'ordering': ['judul'], 'permissions': [('can_add_konten', 'Can add konten'), ('can_change_konten', 'Can change konten'), ('can_delete_konten', 'Can delete konten'), ('can_view_konten', 'Can view konten')], 'verbose_name': 'Konten', 'verbose_name_plural': 'Konten User'},
        ),
        migrations.RenameField(
            model_name='pertanyaan',
            old_name='community',
            new_name='komunitas',
        ),
    ]
