# Generated by Django 5.1.1 on 2024-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0006_alter_konten_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
