# Generated by Django 5.1.1 on 2024-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0007_alter_pertanyaan_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='isi',
            field=models.TextField(),
        ),
    ]
