# Generated by Django 5.1.1 on 2024-12-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cms', '0008_alter_pertanyaan_isi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pertanyaan',
            options={'verbose_name': 'Pertanyaan', 'verbose_name_plural': 'Pertanyaan Komunitas'},
        ),
    ]
