# Generated by Django 5.1.1 on 2024-12-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cms', '0001_initial'),
        ('user_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontendilihat',
            name='konten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilihats', to='user_cms.konten'),
        ),
        migrations.AddField(
            model_name='kontendilihat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peraturankomunitas',
            name='komunitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.komunitas'),
        ),
        migrations.AlterUniqueTogether(
            name='konfigurasi',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='kontendilihat',
            unique_together={('konten', 'user')},
        ),
    ]
