# Generated by Django 5.1.1 on 2024-11-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konten',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='konten',
            name='user',
        ),
    ]
