# Generated by Django 5.1.1 on 2024-11-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0002_remove_konten_kategori_remove_konten_user'),
        ('user_cms', '0002_konten_alter_komen_konten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontendilihat',
            name='konten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilihats', to='user_cms.konten'),
        ),
        migrations.DeleteModel(
            name='Konten',
        ),
    ]
