# Generated by Django 5.1.1 on 2024-12-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='foto',
        ),
        migrations.AlterField(
            model_name='konfigurasi',
            name='iklan',
            field=models.ImageField(blank=True, help_text='Masukkan Gambar yang telah disepakati', null=True, upload_to='gambar_iklan/'),
        ),
        migrations.AlterField(
            model_name='konfigurasi',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='konfigurasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
