# Generated by Django 5.1.1 on 2024-11-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
