# Generated by Django 5.1.1 on 2024-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0003_alter_kontendilihat_konten_delete_konten'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfigurasi',
            name='url_iklan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='konfigurasi',
            unique_together={('user',)},
        ),
    ]
