# Generated by Django 5.1.1 on 2024-11-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0004_rename_judul_komunitas_nama_komunitas_tanggal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterModelOptions(
            name='aktivitas',
            options={'verbose_name': 'Aktivitas', 'verbose_name_plural': 'Aktivitas User'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri-Galeri'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori-Kategori'},
        ),
        migrations.AlterModelOptions(
            name='komunitas',
            options={'verbose_name': 'Komunitas', 'verbose_name_plural': 'Komunitas-Komunitas'},
        ),
        migrations.AlterModelOptions(
            name='konfigurasi',
            options={'verbose_name': 'Konfigurasi Admin', 'verbose_name_plural': 'Konfigurasi Admin'},
        ),
        migrations.AlterModelOptions(
            name='kontendilihat',
            options={'verbose_name': 'Konten Dilihat', 'verbose_name_plural': 'Konten Dilihat'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User-User'},
        ),
    ]
