# Generated by Django 5.1.1 on 2024-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0004_remove_bookmarks_komunitas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komunitas',
            name='boomark',
        ),
        migrations.RemoveField(
            model_name='komunitas',
            name='peraturan',
        ),
        migrations.AddField(
            model_name='komunitas',
            name='boomark',
            field=models.ManyToManyField(null=True, to='admin_cms.bookmarks'),
        ),
        migrations.AddField(
            model_name='komunitas',
            name='peraturan',
            field=models.ManyToManyField(null=True, to='admin_cms.peraturankomunitas'),
        ),
    ]
