# Generated by Django 5.1.1 on 2024-12-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0005_remove_komunitas_boomark_remove_komunitas_peraturan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='komunitas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='admin_cms.komunitas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peraturankomunitas',
            name='komunitas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peraturan_komunitas', to='admin_cms.komunitas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komunitas',
            name='boomark',
            field=models.ManyToManyField(related_name='komunitas_bookmarks', to='admin_cms.bookmarks'),
        ),
        migrations.AlterField(
            model_name='komunitas',
            name='peraturan',
            field=models.ManyToManyField(related_name='komunitas_peraturan', to='admin_cms.peraturankomunitas'),
        ),
    ]
