# Generated by Django 5.1.1 on 2024-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0005_delete_carousel_alter_aktivitas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komunitas',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
