# Generated by Django 5.1.1 on 2024-11-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0006_komunitas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='komunitas',
            name='jumlah_pertanyaan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
