# Generated by Django 5.1.1 on 2024-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0007_komunitas_jumlah_pertanyaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='komunitas',
            name='foto_komunitas',
            field=models.ImageField(default='', upload_to='komunitas_foto/'),
            preserve_default=False,
        ),
    ]
