# Generated by Django 5.1.1 on 2024-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0008_komunitas_foto_komunitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komunitas',
            name='foto_komunitas',
            field=models.ImageField(blank=True, null=True, upload_to='komunitas_foto/'),
        ),
    ]
