# Generated by Django 5.1.1 on 2024-12-05 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0009_alter_komunitas_foto_komunitas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='komunitas',
            options={'verbose_name': 'Komunitas', 'verbose_name_plural': 'Komunitas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='komunitas',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
