# Generated by Django 5.1.1 on 2024-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0010_rename_alamat_url_konfigurasi_url_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeri',
            name='judul',
        ),
        migrations.AddField(
            model_name='galeri',
            name='url_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
