# Generated by Django 5.1.1 on 2024-12-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0011_alter_komunitas_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeraturanKomunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=60)),
                ('deskripsi', models.TextField()),
                ('komunitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.komunitas')),
            ],
            options={
                'verbose_name': 'Peraturan Komunitas',
                'verbose_name_plural': 'Peraturan Komunitas',
            },
        ),
    ]
