# Generated by Django 5.1.1 on 2024-12-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0012_peraturankomunitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=155)),
                ('komunitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cms.komunitas')),
            ],
            options={
                'verbose_name': 'Bookmark Komunitas',
                'verbose_name_plural': 'Bookmark Komunitas',
            },
        ),
    ]
