# Generated by Django 5.1.1 on 2024-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0012_galeri_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeri',
            name='url_link',
        ),
        migrations.RemoveField(
            model_name='galeri',
            name='user',
        ),
        migrations.RemoveField(
            model_name='konfigurasi',
            name='url_alamat',
        ),
        migrations.AddField(
            model_name='galeri',
            name='judul',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
