# Generated by Django 5.1.1 on 2024-12-15 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0013_remove_galeri_url_link_remove_galeri_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeri',
            old_name='judul',
            new_name='url_link',
        ),
        migrations.RemoveField(
            model_name='galeri',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='galeri',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
