# Generated by Django 5.1.1 on 2024-12-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0014_rename_judul_galeri_url_link_remove_galeri_tanggal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeri',
        ),
    ]
