# Generated by Django 5.1.1 on 2024-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cms', '0015_delete_galeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfigurasi',
            name='url_alamat',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
